[package]
name = "gtav-helpers"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Helper Programs for GTA V Speedrunning"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
chrono = "0.4.8"